\c yag;

INSERT INTO games.companies(id, name) VALUES (1000000, 'Седьмой волк');
INSERT INTO games.companies(id, name) VALUES (1000001, 'Yavsoft');
INSERT INTO games.companies(id, name) VALUES (1000002, 'Sibart');
INSERT INTO games.companies(id, name) VALUES (1000003, 'Vochozka Trading');
INSERT INTO games.companies(id, name) VALUES (1000004, 'LucasFan Games');
INSERT INTO games.companies(id, name) VALUES (1000005, 'Computer Support Corporation');
INSERT INTO games.companies(id, name) VALUES (1000006, 'TLC Tewi Verlag GmbH');
INSERT INTO games.companies(id, name) VALUES (1000007, 'Midisoft Corporation');
INSERT INTO games.companies(id, name) VALUES (1000008, 'Limesoft');
INSERT INTO games.companies(id, name) VALUES (1000009, 'Plasma Entertainment');
INSERT INTO games.companies(id, name) VALUES (1000010, 'Sampo Oy');
INSERT INTO games.companies(id, name) VALUES (1000011, 'So\USE Interactive Entertainment');
INSERT INTO games.companies(id, name) VALUES (1000012, 'Artefact');
INSERT INTO games.companies(id, name) VALUES (1000013, 'Abudoe Software, Inc.');
INSERT INTO games.companies(id, name) VALUES (1000014, 'Harper Kids Interactive');
INSERT INTO games.companies(id, name) VALUES (1000015, 'Walt Disney Records');
INSERT INTO games.companies(id, name) VALUES (1000016, 'Micrografx');
INSERT INTO games.companies(id, name) VALUES (1000017, 'Little Ark Interactive');
