CREATE USER portsvc WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT ENCRYPTED PASSWORD '********';
GRANT CONNECT ON DATABASE yag TO portsvc;

GRANT USAGE ON SCHEMA games TO portsvc;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA games TO portsvc;
GRANT ALL ON ALL TABLES IN SCHEMA games TO portsvc;

REVOKE ALL PRIVILEGES ON SCHEMA games FROM mccsvc;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA games FROM mccsvc;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA games FROM mccsvc;
